
src_files = [
    'xd_server_base.c',
    'xd_worker_pool.c',
    'xd_log.c',
    'xd_locker.c'
]

base_src_files = [
    'xd_worker_pool.c',
    'xd_log.c',
    'xd_locker.c'
]

StaticLibrary('base', base_src_files)

libs = [
    'pthread',
    'base',
    'event'
]
#libs=[]

import os,sys
if sys.platform.startswith('darwin'):
    CFLAGS = " -I/usr/local/include "
    LIBPATH = [".", "/usr/local/lib"]
else:
    CFLAGS = " "
    LIBPATH = ["."]

Program('ut', 'test.c',CFLAGS=CFLAGS,LIBS=libs, LIBPATH=LIBPATH)
Program('xx', 'xd_server_base.c', CFLAGS=CFLAGS,LIBS=libs, LIBPATH=LIBPATH)
