
src_files = [
    'xd_server_base.c',
    'xd_worker_pool.c',
    'xd_log.c',
    'xd_locker.c'
]

base_src_files = [
    'xd_worker_pool.c',
    'xd_log.c',
    'xd_locker.c'
]

StaticLibrary('base', base_src_files)

libs = [
    'pthread',
    'base'
]
#libs=[]
Program('ut', 'test.c', LIBS=libs, LIBPATH='.')
